version: '3'
services:
  redpanda1:
    environment:
      - DEB_PATH
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 4
      context: .
      dockerfile: ./docker/redpanda/Dockerfile
    privileged: true
    container_name: redpanda1
    hostname: redpanda1
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/redpanda1/mnt/vectorized/redpanda:/mnt/vectorized/redpanda
      - $DEB_PATH:/mnt/vectorized/redpanda.deb
  redpanda2:
    environment:
      - DEB_PATH
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 4
      context: .
      dockerfile: ./docker/redpanda/Dockerfile
    depends_on:
      - "redpanda1"
    privileged: true
    container_name: redpanda2
    hostname: redpanda2
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/redpanda2/mnt/vectorized/redpanda:/mnt/vectorized/redpanda
      - $DEB_PATH:/mnt/vectorized/redpanda.deb
  redpanda3:
    environment:
      - DEB_PATH
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 4
      context: .
      dockerfile: ./docker/redpanda/Dockerfile
    depends_on:
      - "redpanda1"
    privileged: true
    container_name: redpanda3
    hostname: redpanda3
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/redpanda3/mnt/vectorized/redpanda:/mnt/vectorized/redpanda
      - $DEB_PATH:/mnt/vectorized/redpanda.deb
  redpanda4:
    environment:
      - DEB_PATH
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 4
      context: .
      dockerfile: ./docker/redpanda/Dockerfile
    depends_on:
      - "redpanda1"
    privileged: true
    container_name: redpanda4
    hostname: redpanda4
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/redpanda4/mnt/vectorized/redpanda:/mnt/vectorized/redpanda
      - $DEB_PATH:/mnt/vectorized/redpanda.deb
  client1:
    environment:
      - DEB_PATH
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 4
      context: .
      dockerfile: ./docker/client/Dockerfile
    depends_on:
      - "redpanda1"
      - "redpanda2"
      - "redpanda3"
      - "redpanda4"
    privileged: true
    container_name: client1
    hostname: client1
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/client1/mnt/vectorized/workloads/logs:/mnt/vectorized/workloads/logs
      - $DEB_PATH:/mnt/vectorized/redpanda.deb
  control:
    environment:
      - DEB_PATH
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 4
        WORKLOAD_CLUSTER_SIZE: 1
      context: .
      dockerfile: ./docker/control/Dockerfile
    depends_on:
      - "redpanda1"
      - "redpanda2"
      - "redpanda3"
      - "redpanda4"
      - "client1"
    privileged: true
    container_name: control
    hostname: control
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/control/mnt/vectorized/experiments:/mnt/vectorized/experiments
      - $DEB_PATH:/mnt/vectorized/redpanda.deb
networks:
  chaos:
    driver: bridge
