version: '3'
services:
  redpanda1:
    environment:
      - DEB_DIR
      - DEB_FILE_LIST
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 6
      context: .
      dockerfile: ./docker/redpanda/Dockerfile
    privileged: true
    container_name: ${COMPOSE_PROJECT_NAME}-redpanda1
    hostname: redpanda1
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/${COMPOSE_PROJECT_NAME}-redpanda1/mnt/vectorized/redpanda:/mnt/vectorized/redpanda
      - ./docker/bind_mounts/${COMPOSE_PROJECT_NAME}-redpanda1/mnt/vectorized/entrypoint:/mnt/vectorized/entrypoint
      - $DEB_DIR:/mnt/vectorized/deb
  redpanda2:
    environment:
      - DEB_DIR
      - DEB_FILE_LIST
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 6
      context: .
      dockerfile: ./docker/redpanda/Dockerfile
    depends_on:
      - "redpanda1"
    privileged: true
    container_name: ${COMPOSE_PROJECT_NAME}-redpanda2
    hostname: redpanda2
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/${COMPOSE_PROJECT_NAME}-redpanda2/mnt/vectorized/redpanda:/mnt/vectorized/redpanda
      - ./docker/bind_mounts/${COMPOSE_PROJECT_NAME}-redpanda2/mnt/vectorized/entrypoint:/mnt/vectorized/entrypoint
      - $DEB_DIR:/mnt/vectorized/deb
  redpanda3:
    environment:
      - DEB_DIR
      - DEB_FILE_LIST
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 6
      context: .
      dockerfile: ./docker/redpanda/Dockerfile
    depends_on:
      - "redpanda1"
    privileged: true
    container_name: ${COMPOSE_PROJECT_NAME}-redpanda3
    hostname: redpanda3
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/${COMPOSE_PROJECT_NAME}-redpanda3/mnt/vectorized/redpanda:/mnt/vectorized/redpanda
      - ./docker/bind_mounts/${COMPOSE_PROJECT_NAME}-redpanda3/mnt/vectorized/entrypoint:/mnt/vectorized/entrypoint
      - $DEB_DIR:/mnt/vectorized/deb
  redpanda4:
    environment:
      - DEB_DIR
      - DEB_FILE_LIST
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 6
      context: .
      dockerfile: ./docker/redpanda/Dockerfile
    depends_on:
      - "redpanda1"
    privileged: true
    container_name: ${COMPOSE_PROJECT_NAME}-redpanda4
    hostname: redpanda4
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/${COMPOSE_PROJECT_NAME}-redpanda4/mnt/vectorized/redpanda:/mnt/vectorized/redpanda
      - ./docker/bind_mounts/${COMPOSE_PROJECT_NAME}-redpanda4/mnt/vectorized/entrypoint:/mnt/vectorized/entrypoint
      - $DEB_DIR:/mnt/vectorized/deb
  redpanda5:
    environment:
      - DEB_DIR
      - DEB_FILE_LIST
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 6
      context: .
      dockerfile: ./docker/redpanda/Dockerfile
    depends_on:
      - "redpanda1"
    privileged: true
    container_name: ${COMPOSE_PROJECT_NAME}-redpanda5
    hostname: redpanda5
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/${COMPOSE_PROJECT_NAME}-redpanda5/mnt/vectorized/redpanda:/mnt/vectorized/redpanda
      - ./docker/bind_mounts/${COMPOSE_PROJECT_NAME}-redpanda5/mnt/vectorized/entrypoint:/mnt/vectorized/entrypoint
      - $DEB_DIR:/mnt/vectorized/deb
  redpanda6:
    environment:
      - DEB_DIR
      - DEB_FILE_LIST
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 6
      context: .
      dockerfile: ./docker/redpanda/Dockerfile
    depends_on:
      - "redpanda1"
    privileged: true
    container_name: ${COMPOSE_PROJECT_NAME}-redpanda6
    hostname: redpanda6
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/${COMPOSE_PROJECT_NAME}-redpanda6/mnt/vectorized/redpanda:/mnt/vectorized/redpanda
      - ./docker/bind_mounts/${COMPOSE_PROJECT_NAME}-redpanda6/mnt/vectorized/entrypoint:/mnt/vectorized/entrypoint
      - $DEB_DIR:/mnt/vectorized/deb
  client1:
    environment:
      - DEB_DIR
      - DEB_FILE_LIST
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 6
      context: .
      dockerfile: ./docker/client/Dockerfile
    depends_on:
      - "redpanda1"
      - "redpanda2"
      - "redpanda3"
      - "redpanda4"
      - "redpanda5"
      - "redpanda6"
    privileged: true
    container_name: ${COMPOSE_PROJECT_NAME}-client1
    hostname: client1
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/${COMPOSE_PROJECT_NAME}-client1/mnt/vectorized/workloads/logs:/mnt/vectorized/workloads/logs
      - ./docker/bind_mounts/${COMPOSE_PROJECT_NAME}-client1/mnt/vectorized/entrypoint:/mnt/vectorized/entrypoint
      - $DEB_DIR:/mnt/vectorized/deb
  client2:
    environment:
      - DEB_DIR
      - DEB_FILE_LIST
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 6
      context: .
      dockerfile: ./docker/client/Dockerfile
    depends_on:
      - "redpanda1"
      - "redpanda2"
      - "redpanda3"
      - "redpanda4"
      - "redpanda5"
      - "redpanda6"
    privileged: true
    container_name: ${COMPOSE_PROJECT_NAME}-client2
    hostname: client2
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/${COMPOSE_PROJECT_NAME}-client2/mnt/vectorized/workloads/logs:/mnt/vectorized/workloads/logs
      - ./docker/bind_mounts/${COMPOSE_PROJECT_NAME}-client2/mnt/vectorized/entrypoint:/mnt/vectorized/entrypoint
      - $DEB_DIR:/mnt/vectorized/deb
  control:
    environment:
      - DEB_DIR
      - DEB_FILE_LIST
    build:
      args:
        REDPANDA_CLUSTER_SIZE: 6
        WORKLOAD_CLUSTER_SIZE: 2
      context: .
      dockerfile: ./docker/control/Dockerfile
    depends_on:
      - "redpanda1"
      - "redpanda2"
      - "redpanda3"
      - "redpanda4"
      - "redpanda5"
      - "redpanda6"
      - "client1"
      - "client2"
    privileged: true
    container_name: ${COMPOSE_PROJECT_NAME}-control
    hostname: control
    networks:
      - chaos
    volumes:
      - ./docker/bind_mounts/${COMPOSE_PROJECT_NAME}-control/mnt/vectorized/experiments:/mnt/vectorized/experiments
      - ./docker/bind_mounts/${COMPOSE_PROJECT_NAME}-control/mnt/vectorized/entrypoint:/mnt/vectorized/entrypoint
      - $DEB_DIR:/mnt/vectorized/deb
networks:
  chaos:
    driver: bridge
