- name: run chaos testing suite
  hosts: control
  vars:
    suite_path: "test_suite_all.json"
    repeat: 1
  tasks:
    - become_user: ubuntu
      shell: |
        now=$(date +"%s")
        python3 /mnt/vectorized/harness/test.suite.py --run_id $now --suite /mnt/vectorized/suites/{{ suite_path }} --repeat {{ repeat }} > /mnt/vectorized/experiments/latest.log 2>&1
        rm -f /mnt/vectorized/experiments/latest.log
      async: 21600
      poll: 10